var sec = document.getElementById('seconds');
var min = document.getElementById('minutes');
var hr = document.getElementById('hours');
var date = new Date();
sec.innerText = date.getSeconds();
min.innerText = date.getMinutes();
hr.innerText = date.getHours();
setInterval(()=>{date = new Date();
(date.getSeconds()<10)?sec.innerText = `0${date.getSeconds()}`:sec.innerText = date.getSeconds();
(date.getMinutes() < 10)?min.innerText = `0${date.getMinutes()}:`:min.innerText = date.getMinutes()+":";
(date.getHours() < 10)?hr.innerText = `0${date.getHours()}:`:hr.innerText = date.getHours()+":";
}, 1000);